In [2]:
import pandas as pd
import os

os.getcwd()
os.chdir("C:/Users\임상현/Desktop\업무/배출체계/181127_주행거리_재작업")
os.getcwd()
os.listdir(".")

['kt_rawdata',
 'kt_rawdata.zip',
 'output_1.csv',
 'output_2.csv',
 'TS배출 표준코드.xlsx',
 '주행거리연산_결과파일양식1.xlsx',
 '주행거리연산_결과파일양식2.xlsx',
 '주행거리연산_설명서(2).hwp',
 '주행거리연산_작업예시(2).xlsx']

In [129]:
df=pd.read_csv("output_1.csv",encoding='utf-8')
ddf=pd.read_csv("output_2.csv",encoding='utf-8')

In [130]:
os.getcwd()
os.chdir("C:/Users\임상현/Desktop\업무/배출체계/181127_주행거리_재작업/kt_rawdata")
os.getcwd()
os.listdir(".")

df_2=pd.read_csv("kt_trans2_A.txt",sep='\t',encoding='utf-8')
df_2

ddf_2=pd.read_csv("kt_trans2_B.txt",sep='\t',encoding='utf-8')

In [131]:
haha = []
ha=[]

ha=ddf.NCODE
haha=df.NCODE

ddf.index=ha
df.index=haha

ddf

             NCODE  Scode1  Bcode  Ccode1  Ccode2  Fcode  Ycode  N_KT   KT
NCODE
10011111  10011111       1      1       1       1      1      1     0  0.0
10111111  10111111       1      1       1       1      1      1     0  0.0
10211111  10211111       1      1       1       1      1      1     0  0.0
10311111  10311111       1      1       1       1      1      1     0  0.0
10411111  10411111       1      1       1       1      1      1     0  0.0
10511111  10511111       1      1       1       1      1      1     0  0.0
10611111  10611111       1      1       1       1      1      1     0  0.0
10711111  10711111       1      1       1       1      1      1     0  0.0
10811111  10811111       1      1       1       1      1      1     0  0.0
10911111  10911111       1      1       1       1      1      1     0  0.0
11011111  11011111       1      1       1       1      1      1     0  0.0
11111111  11111111       1      1       1       1      1      1     0  0.0
11211111  11211111       1      1       1       1      1      1     0  0.0
11311111  11311111       1      1       1       1      1      1     0  0.0
11411111  11411111       1      1       1       1      1      1     0  0.0
11511111  11511111       1      1       1       1      1      1     0  0.0
11611111  11611111       1      1       1       1      1      1     0  0.0
11711111  11711111       1      1       1       1      1      1     0  0.0
11811111  11811111       1      1       1       1      1      1     0  0.0
11911111  11911111       1      1       1       1      1      1     0  0.0
12011111  12011111       1      1       1       1      1      1     0  0.0
12111111  12111111       1      1       1       1      1      1     0  0.0
12211111  12211111       1      1       1       1      1      1     0  0.0
12311111  12311111       1      1       1       1      1      1     0  0.0
12411111  12411111       1      1       1       1      1      1     0  0.0
13011111  13011111       2      1       1       1      1      1     0  0.0
13111111  13111111       2      1       1       1      1      1     0  0.0
13211111  13211111       2      1       1       1      1      1     0  0.0
13311111  13311111       2      1       1       1      1      1     0  0.0
13411111  13411111       2      1       1       1      1      1     0  0.0
...            ...     ...    ...     ...     ...    ...    ...   ...  ...
36334474  36334474      15      3       4       4      7      4     0  0.0
36434474  36434474      15      3       4       4      7      4     0  0.0
36534474  36534474      15      3       4       4      7      4     0  0.0
36634474  36634474      15      3       4       4      7      4     0  0.0
36734474  36734474      15      3       4       4      7      4     0  0.0
36834474  36834474      15      3       4       4      7      4     0  0.0
36934474  36934474      15      3       4       4      7      4     0  0.0
37034474  37034474      15      3       4       4      7      4     0  0.0
37134474  37134474      15      3       4       4      7      4     0  0.0
37234474  37234474      15      3       4       4      7      4     0  0.0
37334474  37334474      15      3       4       4      7      4     0  0.0
37934474  37934474      16      3       4       4      7      4     0  0.0
38134474  38134474      16      3       4       4      7      4     0  0.0
38334474  38334474      16      3       4       4      7      4     0  0.0
38434474  38434474      16      3       4       4      7      4     0  0.0
38534474  38534474      16      3       4       4      7      4     0  0.0
38634474  38634474      16      3       4       4      7      4     0  0.0
38734474  38734474      16      3       4       4      7      4     0  0.0
38834474  38834474      16      3       4       4      7      4     0  0.0
38934474  38934474      16      3       4       4      7      4     0  0.0
39034474  39034474      16      3       4       4      7      4     0  0.0
39134474  39134474      16      3       4       4      7      4     0  0.0
39234474  39234474      16      3       4       4      7      4     0  0.0
39334474  39334474      16      3       4       4      7      4     0  0.0
39434474  39434474      16      3       4       4      7      4     0  0.0
39534474  39534474      16      3       4       4      7      4     0  0.0
39634474  39634474      16      3       4       4      7      4     0  0.0
39734474  39734474      16      3       4       4      7      4     0  0.0
39834474  39834474      16      3       4       4      7      4     0  0.0
40534474  40534474      17      3       4       4      7      4     0  0.0

[306432 rows x 9 columns]

In [106]:
count=0

while count <= 16490:
    
    a=0
    b=0
    c=0
    
    a=df_2.iloc[count,:].Ncode
    a=int(a)
    
    b=df_2.iloc[count,:].COUNT
    c=df_2.iloc[count,:].Lcode_avg
    
    b=int(b)
    c=float(c)
    
    df.loc[a,'N_KT']=b
    df.loc[a,'KT']=c
    
    count=count+1

In [135]:
count=0

while count <= 43035:
    
    a=0
    b=0
    c=0
    
    a=ddf_2.iloc[count,:].Ncode
    a=int(a)
    
    b=ddf_2.iloc[count,:].COUNT
    c=ddf_2.iloc[count,:].Lcode_avg
    
    b=int(b)
    c=float(c)
    
    ddf.loc[a,'N_KT']=b
    ddf.loc[a,'KT']=c
    
    count=count+1
    
    
    if count%1000 == 0:
        print(count)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000

IndexError: single positional indexer is out-of-bounds

In [108]:
df.to_csv("out_1.csv")

In [138]:
ddf.to_csv("out_2.csv")

In [3]:
import pandas as pd
import os

os.getcwd()
os.chdir("C:/Users/임상현/Desktop/업무/배출체계/181127_주행거리_재작업/kt_rawdata")
os.getcwd()
os.listdir(".")

['2017자동차주행거리통계_마이크로데이터(개인정보제외) - 복사본.txt',
 'kt_trans1_1.txt',
 'kt_trans1_2_new.txt',
 'kt_trans1_2_old.txt',
 'kt_trans2_A.txt',
 'kt_trans2_B.txt',
 'out_1.csv',
 'out_2.csv',
 'text.csv',
 'text_data.txt',
 '[배출체계]주행거리_재작업.zip']

In [4]:
night=pd.read_csv("kt_trans1_2_new.txt",sep=',',encoding='utf-8')

D:\conda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [148]:
night

,Ncode,Scode1,Scode2,Bcode,Ccode1,Ccode2,Fcode,Ocode,Wcode,Lcode,Mcode,LMcode
0,22223324,1,222,2,3,3,2,4.0,2,3.923077,1.287473,5.050854
1,25433324,1,254,3,3,3,2,4.0,2,17.263610,1.109413,19.152471
2,16633474,1,166,3,3,4,7,4.0,2,0.001350,29.757592,0.040159
3,28621214,1,286,2,1,2,1,4.0,2,5.086777,2.895143,14.726947
4,10221414,1,102,2,1,4,1,4.0,2,8.813443,2.872658,25.318007
5,17934424,1,179,3,4,4,2,4.0,2,44.466844,1.333131,59.280123
6,32923224,1,329,2,3,2,2,4.0,2,1.683673,1.232455,2.075052
7,11524324,1,115,2,4,3,2,4.0,2,1.329377,1.291244,1.716549
8,32524424,1,325,2,4,4,2,4.0,2,0.534426,1.354332,0.723791
9,22521414,1,225,2,1,4,1,4.0,2,5.864691,2.849071,16.708921
10,12321414,1,123,2,1,4,1,4.0,2,26.310616,2.872658,75.581401
11,28823324,1,288,2,3,3,2,4.0,2,4.674185,1.406762,6.575465
12,37923324,1,379,2,3,3,2,4.0,2,1.730583,1.370390,2.371573
13,15523424,1,155,2,3,4,2,4.0,2,1.012295,1.414346,1.431736
14,25822234,1,258,2,2,2,3,4.0,2,5.518006,2.449327,13.515401
15,32523424,1,325,2,3,4,2,4.0,2,9.259843,1.363822,12.628779
16,11521414,1,115,2,1,4,1,4.0,2,36.336170,2.464433,89.548057
17,26723324,1,267,2,3,3,2,4.0,2,4.426997,1.377095,6.096397
18,28223324,1,282,2,3,3,2,4.0,2,1.842818,1.389017,2.559706
19,39223324,1,392,2,3,3,2,4.0,2,0.803614,1.370390,1.101265
20,12121414,1,121,2,1,4,1,4.0,2,31.604588,2.872658,90.789173
21,29821314,1,298,2,1,3,1,4.0,2,64.888889,2.752471,178.604800
22,10521414,1,105,2,1,4,1,4.0,2,10.063492,2.872658,28.908971
23,11021414,1,110,2,1,4,1,4.0,2,21.862581,2.872658,62.803718
24,10021414,1,100,2,1,4,1,4.0,2,7.599451,2.872658,21.830624
25,23121414,1,231,2,1,4,1,4.0,2,31.112835,2.849071,88.642681
26,11121414,1,111,2,1,4,1,4.0,2,32.958165,2.872658,94.677534
27,40521414,1,405,2,1,4,1,4.0,2,8.523142,2.967229,25.290115
28,12121414,1,121,2,1,4,1,4.0,2,62.220315,2.872658,178.737683
29,12321414,1,123,2,1,4,1,4.0,2,5.759234,2.872658,16.544309
...,...,...,...,...,...,...,...,...,...,...,...,...
9635737,25221413,1,252,2,1,4,1,3.0,2,17.359364,2.748723,47.716075
9635738,37921412,1,379,2,1,4,1,2.0,2,21.381770,2.735339,58.486390
9635739,35521412,1,355,2,1,4,1,2.0,2,27.659892,2.648763,73.264499
9635740,25121412,1,251,2,1,4,1,2.0,2,24.298551,2.748723,66.789974
9635741,10121412,1,101,2,1,4,1,2.0,2,43.588160,2.872658,125.213874
9635742,15621413,1,156,2,1,4,1,3.0,2,12.710207,2.823076,35.881882
9635743,12121413,1,121,2,1,4,1,3.0,2,5.465050,2.872658,15.699219
9635744,11331412,1,113,3,1,4,1,2.0,2,32.379121,2.031543,65.779581
9635745,25821412,1,258,2,1,4,1,2.0,2,21.824922,2.748723,59.990655
9635746,10521412,1,105,2,1,4,1,2.0,2,10.952989,2.872658,31.464190
9635747,12121412,1,121,2,1,4,1,2.0,2,13.636624,2.872658,39.173356
9635748,23221412,1,232,2,1,4,1,2.0,2,19.936261,2.849071,56.799825
9635749,15521412,1,155,2,1,4,1,2.0,2,8.960608,2.823076,25.296479
9635750,38721412,1,387,2,1,4,1,2.0,2,12.704963,2.735339,34.752380
9635751,14321412,1,143,2,1,4,1,2.0,2,7.484463,2.913708,21.807540
9635752,11821412,1,118,2,1,4,1,2.0,2,43.110012,2.872658,123.840320
9635753,15521412,1,155,2,1,4,1,2.0,2,6.301075,2.823076,17.788415
9635754,11021414,1,110,2,1,4,1,4.0,2,4.891929,2.872658,14.052838
9635755,37921413,1,379,2,1,4,1,3.0,2,14.807966,2.735339,40.504807
9635756,12121413,1,121,2,1,4,1,3.0,2,29.849741,2.872658,85.748096
9635757,15121414,1,151,2,1,4,1,4.0,2,53.060440,2.823076,149.793662
9635758,11221414,1,112,2,1,4,1,4.0,2,82.386332,2.872658,236.667753
9635759,12221414,1,122,2,1,4,1,4.0,2,9.164306,2.872658,26.325916
9635760,33421314,1,334,2,1,3,1,4.0,2,24.239159,2.668456,64.681128
9635761,11321314,1,113,2,1,3,1,4.0,2,11.278308,2.815913,31.758741
9635762,19221314,1,192,2,1,3,1,4.0,2,35.086334,2.708389,95.027430
9635763,20421314,1,204,2,1,3,1,4.0,2,41.721591,2.792793,116.519751
9635764,10821414,1,108,2,1,4,1,4.0,2,17.816689,2.872658,51.181255
9635765,20422373,1,204,2,2,3,7,3.0,2,0.004505,40.651109,0.183113
9635766,22822373,1,228,2,2,3,7,3.0,2,0.004505,40.651109,0.183113

In [14]:
ok1=night.loc[ (night['Fcode']==2) & (night['Ccode1']==3) & (night['Ccode2']==2) & (night['Ocode']==1) ]
ok2=night.loc[ (night['Fcode']==2) & (night['Ccode1']==3) & (night['Ccode2']==2) & (night['Ocode']==2) ]
ok3=night.loc[ (night['Fcode']==2) & (night['Ccode1']==3) & (night['Ccode2']==2) & (night['Ocode']==3) ]
ok4=night.loc[ (night['Fcode']==2) & (night['Ccode1']==3) & (night['Ccode2']==2) & (night['Ocode']==4) ]

ook1=night.loc[ (night['Fcode']==1) & (night['Ccode1']==1) & (night['Ccode2']==3) & (night['Ocode']==1) ]
ook2=night.loc[ (night['Fcode']==1) & (night['Ccode1']==1) & (night['Ccode2']==3) & (night['Ocode']==2) ]
ook3=night.loc[ (night['Fcode']==1) & (night['Ccode1']==1) & (night['Ccode2']==3) & (night['Ocode']==3) ]
ook4=night.loc[ (night['Fcode']==1) & (night['Ccode1']==1) & (night['Ccode2']==3) & (night['Ocode']==4) ]


lok1=night.loc[ (night['Fcode']!=2) & (night['Ccode1']==3) & (night['Ccode2']==2) & (night['Ocode']==1) ]
lok2=night.loc[ (night['Fcode']!=2) & (night['Ccode1']==3) & (night['Ccode2']==2) & (night['Ocode']==2) ]
lok3=night.loc[ (night['Fcode']!=2) & (night['Ccode1']==3) & (night['Ccode2']==2) & (night['Ocode']==3) ]
lok4=night.loc[ (night['Fcode']!=2) & (night['Ccode1']==3) & (night['Ccode2']==2) & (night['Ocode']==4) ]

In [15]:
ok1.Lcode.to_csv('b1.csv')
ok2.Lcode.to_csv('b2.csv')
ok3.Lcode.to_csv('b3.csv')
ok4.Lcode.to_csv('b4.csv')

ook1.Lcode.to_csv('bb1.csv')
ook2.Lcode.to_csv('bb2.csv')
ook3.Lcode.to_csv('bb3.csv')
ook4.Lcode.to_csv('bb4.csv')

lok1.Lcode.to_csv('bbb1.csv')
lok2.Lcode.to_csv('bbb2.csv')
lok3.Lcode.to_csv('bbb3.csv')
lok4.Lcode.to_csv('bbb4.csv')

In [13]:
night

,Unnamed: 0,Ncode,Scode1,Scode2,Bcode,Ccode1,Ccode2,Fcode,Ocode,Wcode,Lcode,Mcode,LMcode
0,0,22223324,1,222,2,3,3,2,4.0,2,3.923077,1.287473,5.050854
1,1,25433324,1,254,3,3,3,2,4.0,2,17.263610,1.109413,19.152471
2,2,16633474,1,166,3,3,4,7,4.0,2,0.001350,29.757592,0.040159
3,3,28621214,1,286,2,1,2,1,4.0,2,5.086777,2.895143,14.726947
4,4,10221414,1,102,2,1,4,1,4.0,2,8.813443,2.872658,25.318007
5,5,17934424,1,179,3,4,4,2,4.0,2,44.466844,1.333131,59.280123
6,6,32923224,1,329,2,3,2,2,4.0,2,1.683673,1.232455,2.075052
7,7,11524324,1,115,2,4,3,2,4.0,2,1.329377,1.291244,1.716549
8,8,32524424,1,325,2,4,4,2,4.0,2,0.534426,1.354332,0.723791
9,9,22521414,1,225,2,1,4,1,4.0,2,5.864691,2.849071,16.708921
10,10,12321414,1,123,2,1,4,1,4.0,2,26.310616,2.872658,75.581401
11,11,28823324,1,288,2,3,3,2,4.0,2,4.674185,1.406762,6.575465
12,12,37923324,1,379,2,3,3,2,4.0,2,1.730583,1.370390,2.371573
13,13,15523424,1,155,2,3,4,2,4.0,2,1.012295,1.414346,1.431736
14,14,25822234,1,258,2,2,2,3,4.0,2,5.518006,2.449327,13.515401
15,15,32523424,1,325,2,3,4,2,4.0,2,9.259843,1.363822,12.628779
16,16,11521414,1,115,2,1,4,1,4.0,2,36.336170,2.464433,89.548057
17,17,26723324,1,267,2,3,3,2,4.0,2,4.426997,1.377095,6.096397
18,18,28223324,1,282,2,3,3,2,4.0,2,1.842818,1.389017,2.559706
19,19,39223324,1,392,2,3,3,2,4.0,2,0.803614,1.370390,1.101265
20,20,12121414,1,121,2,1,4,1,4.0,2,31.604588,2.872658,90.789173
21,21,29821314,1,298,2,1,3,1,4.0,2,64.888889,2.752471,178.604800
22,22,10521414,1,105,2,1,4,1,4.0,2,10.063492,2.872658,28.908971
23,23,11021414,1,110,2,1,4,1,4.0,2,21.862581,2.872658,62.803718
24,24,10021414,1,100,2,1,4,1,4.0,2,7.599451,2.872658,21.830624
25,25,23121414,1,231,2,1,4,1,4.0,2,31.112835,2.849071,88.642681
26,26,11121414,1,111,2,1,4,1,4.0,2,32.958165,2.872658,94.677534
27,27,40521414,1,405,2,1,4,1,4.0,2,8.523142,2.967229,25.290115
28,28,12121414,1,121,2,1,4,1,4.0,2,62.220315,2.872658,178.737683
29,29,12321414,1,123,2,1,4,1,4.0,2,5.759234,2.872658,16.544309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9635737,9635737,25221413,1,252,2,1,4,1,3.0,2,17.359364,2.748723,47.716075
9635738,9635738,37921412,1,379,2,1,4,1,2.0,2,21.381770,2.735339,58.486390
9635739,9635739,35521412,1,355,2,1,4,1,2.0,2,27.659892,2.648763,73.264499
9635740,9635740,25121412,1,251,2,1,4,1,2.0,2,24.298551,2.748723,66.789974
9635741,9635741,10121412,1,101,2,1,4,1,2.0,2,43.588160,2.872658,125.213874
9635742,9635742,15621413,1,156,2,1,4,1,3.0,2,12.710207,2.823076,35.881882
9635743,9635743,12121413,1,121,2,1,4,1,3.0,2,5.465050,2.872658,15.699219
9635744,9635744,11331412,1,113,3,1,4,1,2.0,2,32.379121,2.031543,65.779581
9635745,9635745,25821412,1,258,2,1,4,1,2.0,2,21.824922,2.748723,59.990655
9635746,9635746,10521412,1,105,2,1,4,1,2.0,2,10.952989,2.872658,31.464190
9635747,9635747,12121412,1,121,2,1,4,1,2.0,2,13.636624,2.872658,39.173356
9635748,9635748,23221412,1,232,2,1,4,1,2.0,2,19.936261,2.849071,56.799825
9635749,9635749,15521412,1,155,2,1,4,1,2.0,2,8.960608,2.823076,25.296479
9635750,9635750,38721412,1,387,2,1,4,1,2.0,2,12.704963,2.735339,34.752380
9635751,9635751,14321412,1,143,2,1,4,1,2.0,2,7.484463,2.913708,21.807540
9635752,9635752,11821412,1,118,2,1,4,1,2.0,2,43.110012,2.872658,123.840320
9635753,9635753,15521412,1,155,2,1,4,1,2.0,2,6.301075,2.823076,17.788415
9635754,9635754,11021414,1,110,2,1,4,1,4.0,2,4.891929,2.872658,14.052838
9635755,9635755,37921413,1,379,2,1,4,1,3.0,2,14.807966,2.735339,40.504807
9635756,9635756,12121413,1,121,2,1,4,1,3.0,2,29.849741,2.872658,85.748096
9635757,9635757,15121414,1,151,2,1,4,1,4.0,2,53.060440,2.823076,149.793662
9635758,9635758,11221414,1,112,2,1,4,1,4.0,2,82.386332,2.872658,236.667753
9635759,9635759,12221414,1,122,2,1,4,1,4.0,2,9.164306,2.872658,26.325916
9635760,9635760,33421314,1,334,2,1,3,1,4.0,2,24.239159,2.668456,64.681128
9635761,9635761,11321314,1,113,2,1,3,1,4.0,2,11.278308,2.815913,31.758741
9635762,9635762,19221314,1,192,2,1,3,1,4.0,2,35.086334,2.708389,95.027430
9635763,9635763,20421314,1,204,2,1,3,1,4.0,2,41.721591,2.792793,116.519751
9635764,9635764,10821414,1,108,2,1,4,1,4.0,2,17.816689,2.872658,51.181255
9635765,9635765,20422373,1,204,2,2,3,7,3.0,2,0.004505,40.651109,0.183113
9635766,9635766,22822373,1,228,2,2,3,7,3.0,2,0.004505,40.651109,0.183113

In [178]:
mini=[]
middle=[]

mini.append(ok1.Lcode.mean())
mini.append(ok2.Lcode.mean())
mini.append(ok3.Lcode.mean())
mini.append(ok4.Lcode.mean())

middle.append(ook1.Lcode.mean())
middle.append(ook2.Lcode.mean())
middle.append(ook3.Lcode.mean())
middle.append(ook4.Lcode.mean())

In [179]:
print(mini)
print(middle)

[59.35018976595532, 51.711580965572495, 39.324195820857994, 24.712660518124256]
[27.6739174213718, 38.90995417191915, 25.217764661507427, 22.41174338647218]

In [1]:
ok1

NameError: name 'ok1' is not defined

In [175]:
night.loc[ (night['Fcode']==1) & (night['Ccode1']==3) & (night['Ccode2']==3) & (night['Ocode']==1) ]

,Ncode,Scode1,Scode2,Bcode,Ccode1,Ccode2,Fcode,Ocode,Wcode,Lcode,Mcode,LMcode
21915,11723311,1,117,2,3,3,1,1.0,2,24.902813,4.464212,111.171426
21916,21023311,1,210,2,3,3,1,1.0,2,33.542373,4.427557,148.510762
21920,39023311,1,390,2,3,3,1,1.0,2,70.234450,4.250813,298.553515
21921,35823311,1,358,2,3,3,1,1.0,2,3.239819,4.116271,13.335973
25486,26023311,1,260,2,3,3,1,1.0,2,6.403941,4.271611,27.355148
5875587,20423311,1,204,2,3,3,1,1.0,2,27.720109,4.427557,122.732356